### ISSUE TITLE
Intro tour/walkthrough

### ISSUE THREAD

**Issue by lougroshek** [Hyperobjekt/cpal-components#10]

**Comment by amygroshek** [comment]
May not implement.

**Comment by amygroshek** [comment]
1. Use these buttons to select your explorer view. There are two view options: a map view, and a feeder view that [describe]
2. When in the map view, schools are displayed according to [blah blah standard deviation]. 
3. The map can display schools according to a series of indices and indicators normalized to convey [blah blah]...  
4. Use the filters panel to browse and select different indices and indicators for display on the map.
5. The select menu at the top of the filters panel allows you to select different categories of indices and indicators. 
6. Display an index or indicator on the map by clicking on its interactive scale.
7. Add or "knock out" different standard deviations by selecting subsets of the scale. 
8. The legend shows which (slices?/subsets?) of schools are displayed
8. Search for a school using the search bar in the Explorer navigation bar.
9. Hover individual schools to see a popup with the main indices for that school.
10. Click individual schools to open a new page detailing all the indices and indicators for that school.
11. You can zoom in and out using the map controls.
12. You can also reset the zoom and pan of the map.
13. This button allows you to download an image of the map in its present state.
14. The map also contains additional layers, which can be displayed using the map layer toggle.
9. [in feeder view] The feeder view displays all of the feeder schools "fed" by different elementary and middle schools in the district. These feeders are sorted by the the Community Resource Index (CRI), the main index in the Explorer. 
10. The feeder view also displays all of the schools in the district, distributed according to their CRI score. 
11. Click individual feeders to see more information about them. 
12. The legend displays additional information about the feeder and its schools.
13. The distribution chart also highlights all of a feeder's schools when a feeder is selected.
14. Search for a school using the search bar in the navigation menu. This will "lock in" the school's feeder and highlight the school in the distribution chart.
15. For both views, the info panel contains additional information about the interface and its use.
