### ISSUE TITLE
Feeder pattern view

### ISSUE THREAD

**Issue by amygroshek** [Hyperobjekt/cpal-components#11]
- [x] Implement switching between map and feeder pattern views
- [x] Implement feeder pattern charts display
- [x] Implement feeder pattern hover tooltip for charts
- [x] Implement feeder pattern school "index"

**Comment by amygroshek** [comment]
@james-minton Question here: What happens to the filter buttons during the feeder view? Are they hidden? Are there other buttons?

**Comment by amygroshek** [comment]
Additional tasks: 
- [ ] Rebuild feeder bar chart so it looks like eviction tracker
- [ ] Keep mouseover interaction
- [ ] Implement click interaction that "locks" view onto a feeder
- [ ] Bars labeled like with the eviction tracker

**Comment by james-minton** [comment]
@amygroshek (Lou) I see the latest push, where you've removed the filter in that view, and I think it works!

**Comment by amygroshek** [comment]
- [ ] Change feeder bars to look like the attached #3

![JM Feeder pattern bars options](https://user-images.githubusercontent.com/746182/88847055-1b404b80-d1ac-11ea-8900-63593c225cb4.jpg)
