### ISSUE TITLE
Basic map component implemented and loading data

### ISSUE THREAD

**Issue by amygroshek** [Hyperobjekt/cpal-components#3]
Get the basic map component implemented and loading data for schools

- [] Map loads mapbox style
- [] Map has basic zoom in/out controls 
- [] Map displays school data using CRI value
- [] Map responds as needed to changes in device width

**Comment by Lane** [comment]
hey @amygroshek, i have a core map base module that could potentially be repurposed that is based off of [react-map-gl](https://github.com/visgl/react-map-gl).  

  - Base module is here: https://github.com/Hyperobjekt/seda-map/tree/release/v1.1.0/src/modules/map
  - Implementation of the seda map using the module above is here: https://github.com/Hyperobjekt/seda-map/tree/release/v1.1.0/src/modules/explorer/components/map

use whatever makes most sense to you, just a heads up in case it might help

**Comment by amygroshek** [comment]
Thanks @Lane. I was looking over that yesterday. :)

**Comment by Lane** [comment]
Great! As long as it was the one in the `release/v1.1.0` branch, would not recommend using anything from the `master` branch.  It's outdated and doesn't have the same modular structure as `release/v1.1.0`.
