### ISSUE TITLE
Feeder distribution chart school interaction 

### ISSUE THREAD

**Issue by lougroshek** [Hyperobjekt/cpal-components#65]
- [ ] Display school popup contents in feeder view

**Comment by amygroshek** [comment]
@james-minton This was discussed in the meeting, has the client confirmed that they want this?

**Comment by james-minton** [comment]
Thanks for checking, I thought this was meant to be a direct link to the school profile page, not a popup like in the map view ... is there a good reason to do both (or not?), or is the link sufficient? (Discuss in Slack?)

**Comment by lougroshek** [comment]
Won't fix for now.
